--YC1
CREATE DATABASE BTXOAYBANG
--DROP DATABASE BTXOAYBANG
USE BTXOAYBANG;

--DROP TABLE BANGDIEM
CREATE TABLE BANGDIEM
(
	MASV char(7),
	MON nvarchar(20),
	DIEM float,
);

INSERT INTO BANGDIEM VALUES ('1712801', N'Toán', 8.5);
INSERT INTO BANGDIEM VALUES ('1712802', N'Lý', 8.5);
INSERT INTO BANGDIEM VALUES ('1712802', N'Lý', 9);
INSERT INTO BANGDIEM VALUES ('1712803', N'Lý', 8.5);
INSERT INTO BANGDIEM VALUES ('1712803', N'Hóa', 7);

SELECT * FROM BANGDIEM;

--YC2
SELECT *
FROM
(SELECT MASV, MON, DIEM FROM BANGDIEM) BANGNGUON
PIVOT
(
	MAX(DIEM)
	FOR MON IN ([Toán], [Lý], [Hóa])
) BANGCHUYEN;






